apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testnet-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - wsstestnet2.opticonomy.com
    secretName: rpc-tls
  rules:
  - host: wsstestnet2.opticonomy.com
    http:
      paths:
      - path: /rpc
        pathType: Prefix
        backend:
          service:
            name: opticonomy-node-opticonomy-node-rpc
            port:
              number: 9953
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: opticonomy-node-opticonomy-node-rpc
            port:
              number: 9964