apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testnet-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "opticonomy-node-opticonomy-node-rpc"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
  - hosts:
    - wsstestnet2.opticonomy.com
    secretName: rpc-tls
  rules:
  - host: wsstestnet2.opticonomy.com
    http:
      paths:
      - path: /rpc
        pathType: Prefix
        backend:
          service:
            name: opticonomy-node-opticonomy-node-rpc
            port:
              number: 9953
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: opticonomy-node-opticonomy-node-rpc
            port:
              number: 9964
      - path: /archive-rpc
        pathType: Prefix
        backend:
          service:
            name: opticonomy-node-opticonomy-node-archive
            port:
              number: 9933
      - path: /archive-ws
        pathType: Prefix
        backend:
          service:
            name: opticonomy-node-opticonomy-node-archive
            port:
              number: 9944