controller:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:region:account-id:certificate/certificate-id"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
  extraArgs:
    enable-ssl-passthrough: ""
  ingressClassResource:
    name: nginx
    controllerValue: "k8s.io/ingress-nginx"
defaultBackend:
  enabled: false