apiVersion: v1
kind: Service
metadata:
  name: rpc-proxy-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: rpc-proxy
  ports:
    - name: rpc
      port: 80
      targetPort: 80