apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rpc-ws
  labels:
    app: {{ .Release.Name }}-rpc-ws
spec:
  type: LoadBalancer
  ports:
    - port: 9953
      targetPort: 9953
      name: rpc
    - port: 9964
      targetPort: 9964
      name: ws
  selector:
    app: {{ .Values.nodeConfig.name }}