apiVersion: v1
kind: Service
metadata:
  name: rpc-node-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: opticonomy-node
  ports:
  - name: ws
    port: 9964
    targetPort: 9964
