replicaCount: 1

image:
  repository: dimkobo/opticonomy-testnet-node
  tag: amd64
  pullPolicy: Always

nodeConfig:
  basePath: /data/node2
  chain: ./opticonomy-public-testnet-raw.json
  name: validatornode
  keyFile: ./scripts/Node2_keyfile
  keystorePath: ./scripts/Node2_keystore
  port: 30433
  rpcPort: 9943
  wsPort: 9954
  telemetryUrl: "wss://telemetry.polkadot.io/submit/ 0"
  pruning: 250
  bootnodes: /dns/bootnode1.opticonomy.com/tcp/30333/p2p/12D3KooWEDRxtuno5Psd4gBXh1RzouWQPUBAaCiCTkkYrKoTBjYP
  validator: true
  rpcCors: null
  rpcMethods: Safe
  exposeExternal:
    ws: false
    rpc: false
  labels:
    app: validator-node
  


resources:
  limits:
    cpu: "0.5"
    memory: "1Gi"
  requests:
    cpu: "0.5"
    memory: "1Gi"

persistence:
  enabled: true
  size: 10Gi

service:
  type: ClusterIP
  # rpcPort: 9943
  # wsPort: 9954
  p2pPort: 30433