replicaCount: 1

image:
  repository: dimkobo/opticonomy-testnet-node
  tag: latest
  pullPolicy: Always

nodeConfig:
  basePath: /data/node1
  chain: /opticonomy-public-testnet-raw.json
  name: ValidatorNode
  keyFile: /scripts/Node1_keyfile
  keystorePath: /scripts/Node1_keystore
  port: 30433
  rpcPort: 9943
  wsPort: 9954
  telemetryUrl: "wss://telemetry.polkadot.io/submit/ 0"
  args:
    - "--validator"

resources:
  limits:
    cpu: "1"
    memory: "2Gi"
  requests:
    cpu: "0.5"
    memory: "1Gi"

persistence:
  enabled: true
  size: 10Gi

service:
  type: ClusterIP  # Ensure it's only accessible within the cluster
  ports:
    - name: p2p
      port: 30433
      targetPort: 30433
    - name: rpc
      port: 9943
      targetPort: 9943
    - name: ws
      port: 9954
      targetPort: 9954
