replicaCount: 1

image:
  repository: dimkobo/opticonomy-testnet-node
  tag: amd64
  pullPolicy: Always

nodeConfig:
  basePath: /data/node1
  chain: ./opticonomy-public-testnet-raw.json
  name: archivenode
  keyFile: ./scripts/Node1_keyfile
  keystorePath: ./scripts/Node1_keystore
  port: 30333
  rpcPort: 9933
  wsPort: 9944
  telemetryUrl: "wss://telemetry.polkadot.io/submit/ 0"
  pruning: archive
  bootnodes: /dns/bootnode1.opticonomy.com/tcp/30333/p2p/12D3KooWEDRxtuno5Psd4gBXh1RzouWQPUBAaCiCTkkYrKoTBjYP
  validator: true
  rpcCors: null
  rpcMethods: Safe


resources:
  limits:
    cpu: "0.5"
    memory: "1Gi"
  requests:
    cpu: "0.5"
    memory: "1Gi"

persistence:
  enabled: true
  size: 10Gi
  
service:
  type: ClusterIP
  rpcPort: 9933
  wsPort: 9944
  p2pPort: 30333