apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opticonomy-node.fullname" . }}
  labels:
    app: {{ include "opticonomy-node.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "opticonomy-node.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "opticonomy-node.name" . }}
    spec:
      containers:
        - name: opticonomy-node
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --base-path={{ .Values.nodeConfig.basePath }}
            - --chain={{ .Values.nodeConfig.chain}}
            - --name={{ .Values.nodeConfig.name }}
            - --port={{ .Values.nodeConfig.port }}
            - --ws-port={{ .Values.nodeConfig.wsPort }}
            - --rpc-port={{ .Values.nodeConfig.rpcPort }}
            - --telemetry-url={{ .Values.nodeConfig.telemetryUrl }}
            - --pruning={{ .Values.nodeConfig.pruning }}
            - --node-key-file={{ .Values.nodeConfig.keyFile }}
            - --keystore-path={{ .Values.nodeConfig.keystorePath }}
            - --bootnodes={{ .Values.nodeConfig.bootnodes }}
            - --log=network=trace
            - --log=sync=trace
            # - --discover-local
            # - --log=network=debug
            # - --log=sync=debug
            # - --log=rpc=debug
            # - --log=txpool=debug
            # - --reserved-nodes=/ip4/1.2.3.5/tcp/30334/p2p/12D3KooWEDRxtuno5Psd4gBXh1RzouWQPUBAaCiCTkkYrKoTBjYP
            # - --reserved-nodes=/ip4/1.2.3.6/tcp/30335/p2p/12D3KooWEa9rnhRf3uVGqbYEJ7SfnZUnPjvDUiQWE6EqwgeKTMiR
            # - --reserved-only
          ports:
            - containerPort: {{ .Values.service.rpcPort }}
              name: rpc
            - containerPort: {{ .Values.service.wsPort }}
              name: ws
            - containerPort: {{ .Values.service.p2pPort }}
              name: p2p
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
