apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opticonomy-node.fullname" . }}-blockchain
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opticonomy-node.fullname" . }}-keystore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
