apiVersion: v1
kind: Service
metadata:
  name: {{ include "opticonomy-node.fullname" . }}
  labels:
    app: {{ include "opticonomy-node.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.p2pPort }}
      targetPort: {{ .Values.service.p2pPort }}
      name: p2p
  selector:
    app: {{ include "opticonomy-node.name" . }}